version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    networks:
      - mynet
    deploy:
        restart_policy:
            condition: on-failure

  postgresql:
    image: postgres:latest
    networks:
      - mynet
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: shorter
      POSTGRES_USER: gorm
      POSTGRES_PASSWORD: gorm

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
    mynet:
        driver: bridge